-- 創建資料庫
CREATE DATABASE IF NOT EXISTS seat_management;
USE seat_management;

-- 創建Employee表
CREATE TABLE Employee (
    EMP_ID CHAR(5) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    FLOOR_SEAT_SEQ VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_emp_id CHECK (EMP_ID REGEXP '^[0-9]{5}$')
);

-- 創建SeatingChart表
CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ VARCHAR(20) PRIMARY KEY,
    FLOOR_NO VARCHAR(10) NOT NULL,
    SEAT_NO VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 添加外鍵約束
ALTER TABLE Employee
ADD CONSTRAINT fk_floor_seat_seq
FOREIGN KEY (FLOOR_SEAT_SEQ) 
REFERENCES SeatingChart(FLOOR_SEAT_SEQ); 